apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ntx-kubernetes-pod-management.fullname" . }}-pod-reader
  labels:
  {{- include "ntx-kubernetes-pod-management.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources: 
  - serviceaccounts
  verbs: 
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: 
  - get
  - list
- apiGroups:
  - "networking.k8s.io"
  resources: 
  - "ingresses"
  verbs: 
  - "get"
  - "list"