apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ntx-kubernetes-pod-management.fullname" . }}-account
  labels:
  {{- include "ntx-kubernetes-pod-management.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.account.serviceAccount.annotations | nindent 4 }}