apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kubernetes-backend-pod-management
  description: An API to interact with Kubernetes cluster.
  # Example for optional annotations
  annotations:
    github.com/project-slug: noesis-devops/kubernetes-backend-pod-managment
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://10.255.0.155:32014
      title: 'NTX Kubernetes pod management'
spec:
  type: openapi
  owner: group:da-devops
  system: NTX
  lifecycle: development
  apiConsumedBy: ['NTX']
  definition:
    $text: https://github.com/noesis-devops/kubernetes-backend-pod-managment/blob/main/k8s_pod_manager/schema.yml
