apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-{{ port }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-{{ port }}
  template:
    metadata:
      labels:
        app: chrome-{{ port }}
    spec:
      containers:
        - name: chrome-{{ port }}
          image: {{ selenium_node_chrome_image }}
          ports:
            - containerPort: 5555  # Assuming Chrome's debug port
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-{{ port }}-service
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
