apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-{{ port }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub-{{ port }}
  template:
    metadata:
      labels:
        app: selenium-hub-{{ port }}
    spec:
      containers:
        - name: selenium-hub-{{ port }}
          image: {{ selenium_hub_image }}
          ports:
            - containerPort: 4442
              name: publish
            - containerPort: 4443
              name: subscribe
            - containerPort: 4444
              name: hub
          livenessProbe:
            httpGet:
              path: /readyz
              port: 4444
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4444
            initialDelaySeconds: 12
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          env:
            - name: SE_SUB_PATH
              value: /


