{{- if and .Values.chromeNode.enabled ((eq (include "seleniumGrid.useKEDA" .) "true") | ternary (eq .Values.autoscaling.scalingType "deployment") .Values.chromeNode.deploymentEnabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-chrome-node
    app.kubernetes.io/name: selenium-chrome-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.chromeNode.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (not .Values.autoscaling.enableWithExistingKEDA) }}
  replicas: {{ .Values.chromeNode.replicas }}
  {{end}}
  selector:
    matchLabels:
      app: selenium-chrome-node
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- $podScope := deepCopy . -}}
{{- $_ := set $podScope "name" "selenium-chrome-node" -}}
{{- $_ =  set $podScope "node" .Values.chromeNode  -}}
{{- $_ =  set $podScope "uploader" (get .Values.videoRecorder .Values.videoRecorder.uploader) -}}
{{- include "seleniumGrid.podTemplate" $podScope | nindent 2 }}
{{- end }}
