apiVersion: v1
kind: Service
metadata:
  name: android-emulator-{{ port }}-service
spec:
  type: NodePort
  selector:
    app: android-emulator-hub-{{ port }}
  ports:
    - port: 5555
      targetPort: 5555