account:
  serviceAccount:
    annotations: {}
deployment:
  ntxKubernetesPodManagement:
    image:
      repository: ghcr.io/noesis-devops/kubernetes-backend-pod-managment
      tag: 1.1.34
    imagePullPolicy: Always
    imagePullSecrets: dockerconfigjson-github-com
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - nodePort: 32014
    port: 8000
    targetPort: 8000
  type: NodePort
