apiVersion: v1
kind: Service
metadata:
  name: kubernetes-pods-api-management-service
spec:
  selector:
    app: kubernetes-pods-api-management  # Match the labels of your deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000  # Port on which the service will be exposed within the cluster
      targetPort: 8000  # Port your Django app is running on within the pods
      nodePort: 32013  # Port exposed on each node